project:
  type: website
  output-dir: docs

website:
  title: "Curso de Fundamentos en R"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: "Módulos Teóricos"
        menu:
          - text: "Módulo 1"
            file: teoria/Modulo_1.qmd
          # Añade aquí tus otros módulos cuando los muevas
      - text: "Práctica Interactiva"
        menu:
          - text: "Práctica 1"
            file: practica/Practica_Modulo_1.qmd

format:
  html:
    theme: flatly
    toc: true
    css: styles.css

# ESTO ES LO QUE ACTIVA LA MAGIA DE WEBASSEMBLY
filters:
  - r-wasm/live